---
- name: Provision new ubunutu
  hosts: all
  gather_facts: false
  become: yes
  become_user: root
  become_method: sudo
  pre_tasks:
    - name: 'install python2'
      raw: >
        sudo apt-get update -qq;
        apt-get -yq install python-simplejson;
  vars:
    user: ubuntu
  roles:
    - role: micalexander.ufw
      allow_tcp_ports:
        - 22 # ssh
        - 2376 # docker swarm
        - 3376 # docker swarm
    - micalexander.user
    - role: micalexander.python2
      pip2_install: ['powerline-status']
    - micalexander.neovim
    - micalexander.docker
    - micalexander.docker_dev
